-- 1. Force a checkpoint (writes all dirty memory pages out to the actual disk)
CHECKPOINT;

-- 2. Switch to simple recovery to discard the history logs safely
ALTER DATABASE [school] SET RECOVERY SIMPLE;
GO

-- 3. Shrink the .ldf log file down to a compact 10 Megabytes
-- (Note: 'school_log' is the default log file name generated by SSMS)
DBCC SHRINKFILE (school_log, 10);
GO